[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://bot-1791132213-8911-skyred123.bothost.tech/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
